" Maintainer: Bryant Finney

" ----- preferences for normal mode -----
" map original semicolon behavior to new <C-Del> behavior
nnoremap ;; ;

" map semicolon to 'q:'
nmap ; q:


" map ctrl-delete functionality:
nnoremap <C-Del> ved

" map ctrl+shift+delete to delete to the end of the word (instad of moving to
" the beginning of the next)
nnoremap <C-S-Del> vEd

" map ctrl+d to delete the current line
nnoremap <C-D> :dl<Enter>

" map ctrl+backspace to delete the previous word
" nnoremap <C-BS> vbd

" todo: mapping this on top of <C-BS> does strange things on the external
" keyboard
" nnoremap  vbd                         " and the builtin keyboard

" map backspace to delete the previous characer
" nnoremap <BS> X

" map ctrl+left and ctrl+right to move to word boundaries instead of WORD
" boundaries; supplement with ctrl+shift keys
nnoremap <C-Right> e
nnoremap <C-Left> b
nnoremap <C-S-Right> E
nnoremap <C-S-Left> B

" map split transitions for when operating remotely from Windows
nnoremap Wh <C-W><C-H>
nnoremap Wj <C-W><C-j>
nnoremap Wl <C-W><C-l>
nnoremap Wk <C-W><C-K>

" map shift tab to unindent
nnoremap <S-Tab> v<S-<>

" map tab and shift+tab to jump to the next occurence using shemshi
nnoremap <Tab> :Semshi goto name next<CR>
nnoremap <S-Tab> :Semshi goto name prev<CR>

" map 'rr' to replace a node using Semshi
nnoremap rr :Semshi rename<CR>

nnoremap AJ :ALENext<CR>
nnoremap AK :ALEPrevious<CR>

" Open vimagit pane
nnoremap gs :Magit<CR>       " git status

" ----- preferences for insert mode -----
" map ctrl+d to delete the current line
inoremap <C-D> <C-[>:dl<Enter>

" map ctrl+backspace to delete to the beginning of the current word
" inoremap <C-S-BS> <C-[>vBdi

" map ctrl+backspace to delete the previous word
inoremap <C-BS> <C-W>

" map ctrl+bs as ^H this on top of <C-BS> in order to add support outside of gvim
inoremap  <C-W>

" map ctrl+space to overload ctrl+n (for autocomplete)
inoremap <C-Space> <C-P>

" map ctrl+delete this causes the cursor to shift one place to the right when
" deleting the first word on the line
inoremap <C-Del> <C-[>lvedi
" also map the delete key on the laptop's builtin keyboard
" inoremap <C-kDel> <C-[>lvedi

" map ctrl+shift+delete to delete to the end of the WORD
inoremap <C-S-Del> <C-[>lvEhdi
" also map the delete key on the laptop's builtin keyboard
" inoremap <C-S-kDel> <C-[>lvEhdi

" map ctrl+left and ctrl+right to move to word boundaries instead of WORD
" boundaries; supplement with ctrl+shift keys
inoremap <C-Right> <C-[>ea
inoremap <C-Left> <C-[>bi
inoremap <C-S-Right> <C-[>Ea
inoremap <C-S-Left> <C-[>Bi

" map shift tab to unindent
inoremap <S-Tab> <C-[>v<S-<>


" ----- preferences for command mode -----
cmap <C-BS> <C-W>
" legion is a desktop machine, so this is okay-ish:
cmap  <C-W>

" ----- preferences for visual mode -----
" map ctrl+left and ctrl+right to move to word boundaries instead of WORD
" boundaries; supplement with ctrl+shift keys
vnoremap <C-Right> e
vnoremap <C-Left> b
vnoremap <C-S-Right> Eh
vnoremap <C-S-Left> B

" map shift tab to unindent
vnoremap <S-Tab> <S-<>         " TODO: this really needs to be 'delete previous spaces'


" ----- general preferences -----
" colorscheme comes first
colorscheme slate

"set iskeyword-=_
set noautochdir
set backspace=indent,eol,start
set colorcolumn=87
set conceallevel=2
set copyindent
set cursorline
set cursorcolumn
set hlsearch
set nowrap
set number
set preserveindent
set pumheight=10
set showmatch         " toggle showmatch to jump the cursor back to the opening bracket
set smartindent
set tabstop=4 shiftwidth=4 expandtab
set textwidth=87
set whichwrap=b,s,[,]
" configure autocompletion display options
set wildmenu
set wildmode=longest,full

" define a function (called on :w) to remove trailing spaces and to replace
" tab characters with four spaces
fun! TrimWhitespace()
    let l:save = winsaveview()

    %s/\s\+$//e
    %s/\t/    /e
    call winrestview(l:save)
endfun

" configure vim to automatically remove trailing whitespace
autocmd FileType c,cpp,markdown,tex,vim autocmd BufWritePre <buffer> nested :call TrimWhitespace()

" tabs -> spaces on write (for python)
autocmd FileType c,cpp,python autocmd BufWritePre <buffer> nested %s/\t/    /e

" configure vim to automatically format json text on write
com! FormatJSON %!python -m json.tool
autocmd FileType json autocmd BufWritePre <buffer> nested :FormatJSON

" use the black autoformatter for python
"   update 2019-03-18 11:25: ALE should autmatically call black
" autocmd FileType python autocmd BufWritePre <buffer> nested :Black

" use tags generated by ctags and linked into this directory
autocmd BufReadPre *.py setlocal tags=~/.vim/tags

" ----- configure vim-flake8 -----
" let g:flake8_show_in_gutter=1
" let g:flake8_show_in_file=1
" let g:flake8_show_quickfix=1
" execute flake8 on write:
" autocmd BufWritePost *.py call Flake8()

" set originally for matlab, but probably generally useful:
filetype indent on
source $VIMRUNTIME/macros/matchit.vim
source $VIMRUNTIME/ftplugin/man.vim

" configure ALE
let g:ale_completion_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'markdown': ['prettier'],
\   'python': ['black', 'isort', 'autopep8']
\}
let g:ale_lint_on_insert_leave = 1
" mypy is firing a 'No library stub' error
"let g:ale_linters = {
"\   'markdown': ['markdownlint', 'proselint'],
"\   'python': ['flake8', 'pydocstyle', 'mypy', 'bandit'],
"\}
let g:ale_linters = {
\   'markdown': ['markdownlint', 'proselint'],
\   'python': ['flake8'],
\}
let g:ale_list_window_size = 5
let g:ale_open_list = 1
let g:ale_python_auto_pipenv = 1
let g:ale_python_bandit_auto_pipenv = 1
let g:ale_python_flake8_auto_pipenv = 1
let g:ale_python_mypy_auto_pipenv = 1
let g:ale_python_pydocstyle_auto_pipenv = 1
let g:ale_python_pylint_auto_pipenv = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
"let g:ale_set_quickfix = 1
let g:ale_virtualtext_cursor = 1

" configure vim-surround
let g:surround_40 = "(\r)"
let g:surround_91 = "[\r]"
let g:surround_123 = "{\r}"

" configure vim-markdown
let g:vim_markdown_toc_autofit = 1
let g:vim_markdown_conceal = 1

" for future expansion:
let g:airline#extensions#ale#enabled = 1

" ----- configure vim-latex -----
let g:tex_flavor = 'latex'
set sw=2
" TIP: if you write your \label's as \label{fig:something}, then if you
" type in \ref{fig: and press <C-n> you will automatically cycle through
" all the figure labels. Very useful!
set iskeyword+=:


" ----- get plugins through vim-plug (cmd 'Plug')
call plug#begin('~/.vim/plugged')

" Add documentation for the vim-plug wiki
Plug 'https://github.com/junegunn/vim-plug.git'

" Add vim-snippets to allow vim to insert templates with a hotkey
Plug 'https://github.com/honza/vim-snippets.git'

" Add UltiSnips for template insertion
Plug 'SirVer/ultisnips'

" Add vim-latex for editing LaTeX documents
Plug 'vim-latex/vim-latex'

" Add the Black plugin for python development
Plug 'ambv/black'

" Add the Jedi plugin
Plug 'davidhalter/jedi-vim'

" Add the vim-surround plugin for surrounding with quotes, brackets, etc
Plug 'tpope/vim-surround'

" Add plugin for formatting and error checking shell scripts
Plug '42wim/vim-shfmt'

" Add plugin for performing static analysis + style checks with flake8
" Plug 'nvie/vim-flake8'

" Add plugin for checking docstrings with pydocstyle
Plug 'w0rp/ale'

" Add a json formatter plugin
Plug 'elzr/vim-json'

" Add Tabular (dependency of vim-markdown)
Plug 'godlygeek/tabular'

" Add a markdown style checker/formatter
Plug 'plasticboy/vim-markdown'

" Add plugin to auto close parens/braces/brackets/quotes
Plug 'jiangmiao/auto-pairs'

" Add plugin for better python syntax highlighting
Plug 'numirias/semshi', {'do': ':UpdateRemotePlugins'}

" Add plugin for taking notes using RST
Plug 'gu-fan/riv.vim'

" Highlight changes in the gutter
Plug 'airblade/vim-gitgutter'

" Create a pain for showing file diffs
Plug 'jreybert/vimagit'

call plug#end()

set expandtab


" ----- pretty colors -----
func! PrettyColors()
    highlight Comment ctermfg=gray guifg=darkgray

    highlight link pythonDocstring pythonComment
    highlight link pythonOperator pythonStatement

    highlight ColorColumn ctermbg=Black guibg=gray20
    highlight CursorLine guibg=gray20 ctermbg=black
    highlight CursorColumn guibg=gray20 ctermbg=black
    highlight DiffText cterm=bold ctermbg=7 gui=bold guibg=LightGray
    highlight Search ctermfg=248 ctermbg=10 guifg=wheat guibg=peru
    highlight Function guifg=darkgoldenrod
    highlight Include gui=bold cterm=bold ctermfg=5 guifg=plum3
    highlight LineNr ctermfg=LightGray guifg=gray50
    highlight String gui=italic guifg=Turquoise4

    highlight semshiSelected gui=underline cterm=underline ctermbg=LightGray ctermfg=NONE guibg=gray30 guifg=NONE
    highlight semshiImported gui=bold cterm=bold guifg=darkgoldenrod ctermfg=214
    highlight semshiImported guifg=darkgoldenrod ctermfg=214
endfun

fun! GitPrettyColors()
    call PrettyColors()
    highlight Constant ctermfg=69 guifg=CornFlowerBlue
    highlight PreProc cterm=bold gui=bold ctermfg=255 guifg=Grey93
    highlight Identifier cterm=bold gui=bold ctermfg=11 guifg=gold
    highlight gitHead cterm=bold gui=bold ctermfg=14 guifg=cyan
endfun

fun TodoPrettyColors()
    syntax match MyTodo contained "\v.*todo|TODO.*"
    highlight link MyTodo Todo
endf

call PrettyColors()
call TodoPrettyColors()

autocmd FileType markdown,python,sh,vim call PrettyColors()|:call TodoPrettyColors()
autocmd FileType markdown,python,sh,vim call TodoPrettyColors()
autocmd FileType git,gitcommit call GitPrettyColors()
